### ISSUE TITLE
[issue] output inconsistency

### ISSUE THREAD

**Issue by wangchenghku** [wangchenghku/RDMA_Paxos#12]
Weired that the output is inconsistent.

[do_decision] node_id: 0, hashval: 0x13874529797723633967 in round:1
[do_decision] node_id: 1, hashval: 0x13874529797723633967 in round:1
[do_decision] node_id: 2, hashval: 0x13874529797723633967 in round:1
[do_decision] D.0 All hash are the same (Nothing to do)
[do_decision] node_id: 0, hashval: 0x14664192175992564416 in round:1001
[do_decision] node_id: 1, hashval: 0x2915561193030103171 in round:1001
[do_decision] node_id: 2, hashval: 0x10962266538954444631 in round:1001
[hash_consensus] D.3 All nodes need redo.
[do_decision] node_id: 0, hashval: 0x461144612491095103 in round:2001
[do_decision] node_id: 1, hashval: 0x379477500404627858 in round:2001
[do_decision] node_id: 2, hashval: 0x217317425124407410 in round:2001
[hash_consensus] D.3 All nodes need redo.

**Comment by wangchenghku** [comment]
replica 2 log:
count is 1, ret is 5, hash is 13874529797723633967
count is 2, ret is 5, hash is 8864012968218817563
count is 3, ret is 5, hash is 12425007383886198046
count is 4, ret is 5, hash is 5284214607719187812
count is 5, ret is 5, hash is 6446002892321775311
count is 6, ret is 5, hash is 395954375494224354
count is 7, ret is 5, hash is 1556788800738258220
count is 8, ret is 5, hash is 3530229876231611691
count is 9, ret is 5, hash is 16874963934949357214
count is 10, ret is 5, hash is 9126807266861111749
count is 11, ret is 5, hash is 17540217433119034961
count is 12, ret is 5, hash is 17774029526696341266
count is 13, ret is 5, hash is 12929071460871015234
count is 14, ret is 5, hash is 6084246712971217714
count is 15, ret is 5, hash is 13925121320472266489
count is 16, ret is 5, hash is 13077071216817670618
count is 17, ret is 5, hash is 10414021457425313473
count is 18, ret is 5, hash is 13079630675460586247
count is 19, ret is 5, hash is 5584258802556821584
count is 20, ret is 5, hash is 8628993274536252400
count is 21, ret is 5, hash is 10004453063594572605
count is 22, ret is 5, hash is 961407917405813665
count is 23, ret is 5, hash is 9923290085887981944
count is 24, ret is 5, hash is 1857663850068007936
count is 25, ret is 5, hash is 3543006008432209057
count is 26, ret is 5, hash is 11736680046921927489
count is 27, ret is 5, hash is 17344828369426316029
count is 28, ret is 5, hash is 15625577801044225839
count is 29, ret is 5, hash is 13973913550905010423
count is 30, ret is 5, hash is 17494992073821877197
count is 31, ret is 5, hash is 1804896562624135881
count is 32, ret is 5, hash is 5323559056837512764
count is 33, ret is 5, hash is 13097863457229630147
count is 34, ret is 5, hash is 7697530085544395585
count is 35, ret is 5, hash is 1529599390630881727
count is 36, ret is 5, hash is 17205700817115331717
count is 37, ret is 10, hash is 9036441307136566528
count is 38, ret is 5, hash is 4124056698635468402

replica 1 log:
count is 1, ret is 5, hash is 13874529797723633967
count is 2, ret is 5, hash is 8864012968218817563
count is 3, ret is 5, hash is 12425007383886198046
count is 4, ret is 5, hash is 5284214607719187812
count is 5, ret is 5, hash is 6446002892321775311
count is 6, ret is 5, hash is 395954375494224354
count is 7, ret is 5, hash is 1556788800738258220
count is 8, ret is 5, hash is 3530229876231611691
count is 9, ret is 5, hash is 16874963934949357214
count is 10, ret is 5, hash is 9126807266861111749
count is 11, ret is 5, hash is 17540217433119034961
count is 12, ret is 5, hash is 17774029526696341266
count is 13, ret is 5, hash is 12929071460871015234
count is 14, ret is 5, hash is 6084246712971217714
count is 15, ret is 5, hash is 13925121320472266489
count is 16, ret is 5, hash is 13077071216817670618
count is 17, ret is 5, hash is 10414021457425313473
count is 18, ret is 5, hash is 13079630675460586247
count is 19, ret is 5, hash is 5584258802556821584
count is 20, ret is 5, hash is 8628993274536252400
count is 21, ret is 5, hash is 10004453063594572605
count is 22, ret is 5, hash is 961407917405813665
count is 23, ret is 5, hash is 9923290085887981944
count is 24, ret is 5, hash is 1857663850068007936
count is 25, ret is 5, hash is 3543006008432209057
count is 26, ret is 5, hash is 11736680046921927489
count is 27, ret is 5, hash is 17344828369426316029
count is 28, ret is 5, hash is 15625577801044225839
count is 29, ret is 5, hash is 13973913550905010423
count is 30, ret is 5, hash is 17494992073821877197
count is 31, ret is 5, hash is 1804896562624135881
count is 32, ret is 5, hash is 5323559056837512764
count is 33, ret is 5, hash is 13097863457229630147
count is 34, ret is 5, hash is 7697530085544395585
count is 35, ret is 5, hash is 1529599390630881727
count is 36, ret is 5, hash is 17205700817115331717
count is 37, ret is 5, hash is 9613011745075300243

leader log:
count is 1, ret is 5, hash is 13874529797723633967
count is 2, ret is 5, hash is 8864012968218817563
count is 3, ret is 5, hash is 12425007383886198046
count is 4, ret is 5, hash is 5284214607719187812
count is 5, ret is 5, hash is 6446002892321775311
count is 6, ret is 5, hash is 395954375494224354
count is 7, ret is 5, hash is 1556788800738258220
count is 8, ret is 5, hash is 3530229876231611691
[do_decision] node_id: 0, hashval: 0x13874529797723633967 in round:1
[do_decision] node_id: 1, hashval: 0x13874529797723633967 in round:1
[do_decision] node_id: 2, hashval: 0x13874529797723633967 in round:1
[do_decision] D.0 All hash are the same (Nothing to do)
count is 9, ret is 5, hash is 16874963934949357214
count is 10, ret is 5, hash is 9126807266861111749
count is 11, ret is 5, hash is 17540217433119034961
count is 12, ret is 5, hash is 17774029526696341266
[do_decision] node_id: 0, hashval: 0x6446002892321775311 in round:5
[do_decision] node_id: 1, hashval: 0x6446002892321775311 in round:5
[do_decision] node_id: 2, hashval: 0x6446002892321775311 in round:5
[do_decision] D.0 All hash are the same (Nothing to do)
count is 13, ret is 5, hash is 12929071460871015234
count is 14, ret is 5, hash is 6084246712971217714
count is 15, ret is 5, hash is 13925121320472266489
count is 16, ret is 5, hash is 13077071216817670618
[do_decision] node_id: 0, hashval: 0x16874963934949357214 in round:9
[do_decision] node_id: 1, hashval: 0x16874963934949357214 in round:9
[do_decision] node_id: 2, hashval: 0x16874963934949357214 in round:9
[do_decision] D.0 All hash are the same (Nothing to do)
count is 17, ret is 5, hash is 10414021457425313473
count is 18, ret is 5, hash is 13079630675460586247
count is 19, ret is 5, hash is 5584258802556821584
count is 20, ret is 5, hash is 8628993274536252400
[do_decision] node_id: 0, hashval: 0x12929071460871015234 in round:13
[do_decision] node_id: 1, hashval: 0x12929071460871015234 in round:13
[do_decision] node_id: 2, hashval: 0x12929071460871015234 in round:13
[do_decision] D.0 All hash are the same (Nothing to do)
count is 21, ret is 5, hash is 10004453063594572605
count is 22, ret is 5, hash is 961407917405813665
count is 23, ret is 5, hash is 9923290085887981944
count is 24, ret is 5, hash is 1857663850068007936
[do_decision] node_id: 0, hashval: 0x10414021457425313473 in round:17
[do_decision] node_id: 1, hashval: 0x10414021457425313473 in round:17
[do_decision] node_id: 2, hashval: 0x10414021457425313473 in round:17
[do_decision] D.0 All hash are the same (Nothing to do)
count is 25, ret is 5, hash is 3543006008432209057
count is 26, ret is 5, hash is 11736680046921927489
count is 27, ret is 5, hash is 17344828369426316029
count is 28, ret is 5, hash is 15625577801044225839
[do_decision] node_id: 0, hashval: 0x10004453063594572605 in round:21
[do_decision] node_id: 1, hashval: 0x10004453063594572605 in round:21
[do_decision] node_id: 2, hashval: 0x10004453063594572605 in round:21
[do_decision] D.0 All hash are the same (Nothing to do)
count is 29, ret is 5, hash is 13973913550905010423
count is 30, ret is 5, hash is 17494992073821877197
count is 31, ret is 5, hash is 1804896562624135881
count is 32, ret is 5, hash is 5323559056837512764
[do_decision] node_id: 0, hashval: 0x3543006008432209057 in round:25
[do_decision] node_id: 1, hashval: 0x3543006008432209057 in round:25
[do_decision] node_id: 2, hashval: 0x3543006008432209057 in round:25
[do_decision] D.0 All hash are the same (Nothing to do)
count is 33, ret is 5, hash is 13097863457229630147
count is 34, ret is 5, hash is 7697530085544395585
count is 35, ret is 5, hash is 1529599390630881727
count is 36, ret is 5, hash is 17205700817115331717
[do_decision] node_id: 0, hashval: 0x13973913550905010423 in round:29
[do_decision] node_id: 1, hashval: 0x13973913550905010423 in round:29
[do_decision] node_id: 2, hashval: 0x13973913550905010423 in round:29
[do_decision] D.0 All hash are the same (Nothing to do)
count is 37, ret is 5, hash is 9613011745075300243
count is 38, ret is 5, hash is 9036441307136566528
count is 39, ret is 5, hash is 4124056698635468402
count is 40, ret is 5, hash is 2913936047495239879
[do_decision] node_id: 0, hashval: 0x13097863457229630147 in round:33
[do_decision] node_id: 1, hashval: 0x13097863457229630147 in round:33
[do_decision] node_id: 2, hashval: 0x13097863457229630147 in round:33
[do_decision] D.0 All hash are the same (Nothing to do)
count is 41, ret is 5, hash is 4156166104955685404
count is 42, ret is 5, hash is 11141236472891889131
count is 43, ret is 5, hash is 17915219525343588479
count is 44, ret is 5, hash is 4494444203269509338
[do_decision] node_id: 0, hashval: 0x9613011745075300243 in round:37
[do_decision] node_id: 1, hashval: 0x9613011745075300243 in round:37
[do_decision] node_id: 2, hashval: 0x9036441307136566528 in round:37
[do_decision] D.1 Minority need redo.

**Comment by jingleyang** [comment]
Hi @wangchenghku ,
As we discussed, my suggestion is that:
1. try to calculate hash value for every output in order to locate when the output is different.
2. try to print more information, such as the content of buffer and the size of buffer.

Good Luck,
Jingyu

**Comment by wangchenghku** [comment]
primary log:
output idx is 33, hash is 13097863457229630147, ret is 5, content is +OK

output idx is 34, hash is 7697530085544395585, ret is 5, content is +OK

output idx is 35, hash is 1529599390630881727, ret is 5, content is +OK

output idx is 36, hash is 17205700817115331717, ret is 5, content is +OK


replica 1 log:
output idx is 33, hash is 13097863457229630147, ret is 5, content is +OK

output idx is 34, hash is 7697530085544395585, ret is 5, content is +OK

output idx is 35, hash is 9036441307136566528, ret is 20, content is +OK
+OK
+OK
+OK

output idx is 36, hash is 2913936047495239879, ret is 10, content is +OK
+OK
+OK
+OK

replica 2 log:
output idx is 33, hash is 13097863457229630147, ret is 5, content is +OK

output idx is 34, hash is 7697530085544395585, ret is 5, content is +OK

output idx is 35, hash is 1529599390630881727, ret is 5, content is +OK

output idx is 36, hash is 9613011745075300243, ret is 10, content is +OK
+OK

**Comment by wangchenghku** [comment]
interesting things: the replicas have different numbers of outputs
replica 1 log:
output idx is 93, hash is 5931506497584541362, ret is 5, content is +OK

output idx is 94, hash is 2655906701526599542, ret is 5, content is +OK

output idx is 95, hash is 14379829012369671620, ret is 5, content is +OK

output idx is 96, hash is 17944915950203073732, ret is 5, content is +OK

output idx is 97, hash is 13519262223669470667, ret is 5, content is +OK

output idx is 98, hash is 5768319927974050060, ret is 5, content is +OK

output idx is 99, hash is 17826454551597124689, ret is 5, content is +OK

output idx is 100, hash is 13555123974216879804, ret is 5, content is +OK

replica 2 log:
output idx is 94, hash is 14379829012369671620, ret is 10, content is +OK
+OK

output idx is 95, hash is 17944915950203073732, ret is 5, content is +OK
+OK

output idx is 96, hash is 13519262223669470667, ret is 5, content is +OK
+OK

output idx is 97, hash is 5768319927974050060, ret is 5, content is +OK
+OK

output idx is 98, hash is 17826454551597124689, ret is 5, content is +OK
+OK

output idx is 99, hash is 13555123974216879804, ret is 5, content is +OK
+OK

**Comment by jingleyang** [comment]
We solved this issue by using a hash buffer.
